Update jobs.yaml

diff --git a/.github/workflows/jobs.yaml b/.github/workflows/jobs.yaml
--- a/.github/workflows/jobs.yaml
+++ b/.github/workflows/jobs.yaml
@@ -77,10 +77,17 @@ jobs:
         run: |
           databricks_api_token="dapic100eda776087528cd6a82f7ca84914a"
           job_id="${{ steps.job_ids.outputs.job_ids }}"
-          url="url="https://sagerx-aws-devtest-comm.cloud.databricks.com/api/2.1/jobs/get?job_id=${job_id}"
-          payload=""
+          url="https://sagerx-aws-devtest-comm.cloud.databricks.com/api/2.1/jobs/get?job_id=${job_id}"
+          
           response=$(curl -X GET -H "Authorization: Bearer $databricks_api_token" "$url")
-          echo "::set-output name=job_details::${response}"
+          
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=job_details::${response}"
+          else
+            echo "Error: Failed to fetch job details."
+            exit 1
+          fi
+
 
 
 
