Update jobs.yaml

diff --git a/.github/workflows/jobs.yaml b/.github/workflows/jobs.yaml
--- a/.github/workflows/jobs.yaml
+++ b/.github/workflows/jobs.yaml
@@ -75,16 +75,18 @@ jobs:
       - name: Fetch Job Details
         id: fetch_job_details
         run: |
-            databricks_api_token = "dapic100eda776087528cd6a82f7ca84914a"
-            url = "https://sagerx-aws-devtest-comm.cloud.databricks.com/api/2.1/jobs/get?job_id=496296034538647"
-            
-            payload={}
-            headers = {
-                'Authorization': f'Bearer {databricks_api_token}'
-            }
-            response = requests.request("GET", url, headers=headers, data=payload)
-            
-            print(response.text)
+              databricks_api_token="dapic100eda776087528cd6a82f7ca84914a"
+              url="https://sagerx-aws-devtest-comm.cloud.databricks.com/api/2.1/jobs/get?job_id= 496296034538647"
+              
+              response=$(curl -X GET -H "Authorization: Bearer $databricks_api_token" "$url")
+              
+              if [ $? -eq 0 ]; then
+                echo "::set-output name=job_details::${response}"
+              else
+                echo "Error: Failed to fetch job details."
+                exit 1
+              fi
+
 
 
 
